# Информация о сайте
site_name: downwardspiral
site_url: https://docs.basted.ru

# Настройка темы
theme:
  name: material
  language: ru
  logo: assets/images/logo.webp
  favicon: assets/images/favicon.ico

  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb
        name: Переключение в темный режим

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Переключение в светлый режим
  
  features:
    # navigation
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.prune
    - navigation.sections
    - navigation.top
    - navigation.tracking
    
    # search
    - search.highlight
    - search.suggest

    # toc
    - toc.follow

    # code
    - content.code.copy

extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/SpiralNotify_bot
  meta_description: "Документация и лекции по программированию на языке C, Bash и Linux. Учебные материалы, углубленные пояснения и практические советы для студентов и разработчиков. Современные подходы к обучению и созданию программ с акцентом на практическое применение знаний."
  meta_robots: "index, follow"

plugins:
  - git-revision-date-localized
  - privacy
  - search
  - glightbox:
      touchNavigation: true
      loop: false
      effect: zoom
      slide_effect: slide
      width: auto
      height: auto
      zoomable: true
      draggable: true
      auto_caption: false
      caption_position: bottom
      background: white
      shadow: true
      manual: false
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - assets/javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css

copyright: |
  &copy; 2024-2025 <a href="https://basted.ru" target="_blank" rel="noopener">basted</a>

# Page tree
nav:
  - Willkommen: index.md
  - "Билеты и ответы на них": tickets.md
  - YOU GET ME CLOSER TO GOD:
    - "Лекция 1: Введение": closer/first_lecture.md
    - "Лекция 2: Основные этапы решения задач на ЭВМ": closer/second_lecture.md
    - "Лекция 3: Язык C: начальные сведения": closer/third_lecture.md
    - "Лекция 4: Система типов в языке Си": closer/fourth_lecture.md
    - "Лекция 5: Операции, инструкции и выражения": closer/fifth_lecture.md
    - "Лекция 6: Организация ввода-вывода в Си": closer/sixth_lecture.md
    - "Лекция 7: Управляющие инструкции языка": closer/seventh_lecture.md
    - "Лекция 8: Функции": closer/eighth_lecture.md
    - "Лекция 9: Области видимости переменных": closer/nineth_lecture.md
    - "Лекция 10: Одномерные массивы": closer/tenth_lecture.md
    - "Лекция 11: Указатели в языке Си": closer/eleventh_lecture.md
    - "Лекция 12: Указатели и массивы в языке C": closer/twelfth_lecture.md
    - "Лекция 13: Двумерные массивы": closer/thirteenth_lecture.md
    - "Лекция 14: Работа с динамической памятью": closer/fourteenth_lecture.md
    - "Лекция 15: Основы Bash": closer/fifteenth_lecture.md
    - "Лекция 16: Строки в языке Си": closer/sixteenth_lecture.md
    - "Лекция 17: Структуры в языке С": closer/seventeenth_lecture.md
    - "Лекция 18: Файлы в Си и Файловые системы Linux": closer/eighteenth_lecture.md
    - "Лекция 19: Модульное программирование и Инкапсуляция в Си": closer/nineteenth_lecture.md
    - "Лекция 20: Рекурсия": closer/twenty_lecture.md
  - PEOPLE ARE STRANGE:
    - "Почему же Хазиев имеет право называть массивы фикцией?": strange/fiction.md
  - "LEWIS, SAVE YOURSELF THE PAIN":
    - "Массивы и указатели: глубокое погружение": pain/bikini_bottom.md
    - "Всё о работе с ОЗУ в C": pain/ram.md
    - "Использование Linux для будущих C'шников": pain/linux.md
    - "Введение в командную строку (CLI) Linux": pain/cli.md
    - "Права доступа в Linux и команда chmod": pain/chmod.md
    - "Редактор Nano для программистов на C": pain/nano.md
  - "WHERE IS MY MIND?":
    - "I was swimmin' in the Caribbean": mind/caribbean.md
